FROM microsoft/dotnet:2.1.302-sdk AS build
WORKDIR /app

# copy csproj and restore as distinct layers
WORKDIR /app
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
WORKDIR /app
COPY . .
WORKDIR /app
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1.2-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "dotnetcore-docker-sample.dll"]